"""detect schema drift

Revision ID: a253b97201e8
Revises: 001_initial
Create Date: 2026-03-24 09:32:23.541342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a253b97201e8'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('endpoint_agents', 'node_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'workspace'::character varying"))
    op.drop_index(op.f('ix_threat_intel_client_id'), table_name='threat_intel')
    op.drop_constraint(op.f('threat_intel_client_id_fkey'), 'threat_intel', type_='foreignkey')
    op.drop_column('threat_intel', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threat_intel', sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('threat_intel_client_id_fkey'), 'threat_intel', 'clients', ['client_id'], ['id'])
    op.create_index(op.f('ix_threat_intel_client_id'), 'threat_intel', ['client_id'], unique=False)
    op.alter_column('endpoint_agents', 'node_type',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'workspace'::character varying"))
    # ### end Alembic commands ###
