#!/bin/bash
# ============================================================
# AEGIS Autonomous Defense Platform - Installer
# Usage: curl -fsSL https://install.aegis.com | bash
#    or: bash scripts/install.sh
# ============================================================

set -euo pipefail

AEGIS_DIR="${AEGIS_DIR:-$HOME/aegis}"
REPO_URL="${AEGIS_REPO:-https://github.com/aegis-defense/aegis}"
BRANCH="${AEGIS_BRANCH:-main}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

banner() {
    echo ""
    echo -e "${CYAN}${BOLD}"
    echo "   ______                __         ____  "
    echo "  / ____/___ ___  ______/ /__      / __ \\ "
    echo " / /   / __ \`/ / / / __  / _ \\    / / / / "
    echo "/ /___/ /_/ / /_/ / /_/ /  __/   / /_/ /  "
    echo "\\____/\\__,_/\\__, /\\__,_/\\___/    \\____/   "
    echo "           /____/                          "
    echo ""
    echo "  Autonomous Defense Platform v1.0.0"
    echo -e "${NC}"
    echo ""
}

log()   { echo -e "${GREEN}[+]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
error() { echo -e "${RED}[x]${NC} $1"; }
info()  { echo -e "${CYAN}[*]${NC} $1"; }

# --- Pre-flight checks ---

check_docker() {
    if ! command -v docker &> /dev/null; then
        error "Docker is not installed."
        echo ""
        echo "  Install Docker:"
        echo "    Linux:  curl -fsSL https://get.docker.com | sh"
        echo "    macOS:  brew install --cask docker"
        echo "    Windows: https://docs.docker.com/desktop/install/windows-install/"
        echo ""
        exit 1
    fi

    if ! docker info &> /dev/null; then
        error "Docker daemon is not running. Start Docker and try again."
        exit 1
    fi

    log "Docker found: $(docker --version)"
}

check_compose() {
    if docker compose version &> /dev/null; then
        COMPOSE_CMD="docker compose"
    elif command -v docker-compose &> /dev/null; then
        COMPOSE_CMD="docker-compose"
    else
        error "Docker Compose is not installed."
        echo "  Install: https://docs.docker.com/compose/install/"
        exit 1
    fi
    log "Docker Compose found: $($COMPOSE_CMD version --short 2>/dev/null || $COMPOSE_CMD version)"
}

check_ports() {
    local ports=("8000" "3000" "5432")
    for port in "${ports[@]}"; do
        if lsof -i ":$port" &> /dev/null 2>&1 || ss -tlnp 2>/dev/null | grep -q ":$port "; then
            warn "Port $port is already in use. AEGIS may fail to start."
            warn "  You can change ports in .env (AEGIS_API_PORT, FRONTEND_PORT, POSTGRES_PORT)"
        fi
    done
}

# --- Generate secrets ---

generate_secret() {
    # Generate a 32-byte random hex string
    if command -v openssl &> /dev/null; then
        openssl rand -hex 32
    elif [ -f /dev/urandom ]; then
        head -c 32 /dev/urandom | xxd -p | tr -d '\n'
    else
        # Fallback: use date + random
        echo "aegis-$(date +%s)-$(shuf -i 100000-999999 -n1)-$(shuf -i 100000-999999 -n1)"
    fi
}

# --- Setup ---

setup_directory() {
    if [ -d "$AEGIS_DIR" ]; then
        warn "Directory $AEGIS_DIR already exists."
        read -rp "  Overwrite configuration? (y/N): " confirm
        if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
            info "Keeping existing installation. Running docker compose up..."
            cd "$AEGIS_DIR"
            $COMPOSE_CMD up -d
            exit 0
        fi
    fi

    mkdir -p "$AEGIS_DIR"
    log "Install directory: $AEGIS_DIR"
}

clone_or_download() {
    if command -v git &> /dev/null; then
        if [ -d "$AEGIS_DIR/.git" ]; then
            log "Updating existing repository..."
            cd "$AEGIS_DIR"
            git pull origin "$BRANCH" 2>/dev/null || true
        else
            log "Cloning AEGIS repository..."
            git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$AEGIS_DIR" 2>/dev/null || {
                warn "Git clone failed. If running locally, ensure files are in $AEGIS_DIR"
            }
        fi
    else
        warn "Git not found. Downloading release archive..."
        curl -fsSL "$REPO_URL/archive/refs/heads/$BRANCH.tar.gz" -o /tmp/aegis.tar.gz
        tar xzf /tmp/aegis.tar.gz -C "$AEGIS_DIR" --strip-components=1
        rm -f /tmp/aegis.tar.gz
    fi
    cd "$AEGIS_DIR"
}

create_env() {
    local secret_key
    secret_key=$(generate_secret)
    local pg_password
    pg_password=$(generate_secret | head -c 24)

    if [ -f ".env" ]; then
        warn ".env already exists. Creating .env.new instead."
        ENV_FILE=".env.new"
    else
        ENV_FILE=".env"
    fi

    cat > "$ENV_FILE" <<ENVEOF
# AEGIS Autonomous Defense Platform
# Generated by install.sh on $(date -Iseconds 2>/dev/null || date)

# Core
AEGIS_ENV=production
AEGIS_SECRET_KEY=${secret_key}
AEGIS_API_PORT=8000

# AI Provider (set one)
OPENROUTER_API_KEY=
OPENROUTER_BASE_URL=https://openrouter.ai/api/v1

# Database (managed by Docker)
POSTGRES_HOST=aegis-db
POSTGRES_PORT=5432
POSTGRES_DB=aegis
POSTGRES_USER=aegis
POSTGRES_PASSWORD=${pg_password}
DATABASE_URL=postgresql+asyncpg://aegis:${pg_password}@aegis-db:5432/aegis

# Event Bus
USE_MEMORY_BUS=true
REDIS_URL=redis://aegis-redis:6379

# Scanning tools (inside container)
NUCLEI_PATH=nuclei
NMAP_PATH=/usr/bin/nmap
SUBFINDER_PATH=subfinder
HTTPX_PATH=httpx

# Notifications (optional)
WEBHOOK_URL=
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=

# Frontend
FRONTEND_PORT=3000
NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws
ENVEOF

    log "Environment file created: $ENV_FILE"
    if [ "$ENV_FILE" = ".env.new" ]; then
        warn "Review .env.new and rename to .env when ready."
    fi
}

build_and_start() {
    info "Building Docker images (this may take a few minutes)..."
    $COMPOSE_CMD build --no-cache

    info "Starting AEGIS services..."
    $COMPOSE_CMD up -d

    info "Waiting for services to become healthy..."
    local max_wait=120
    local elapsed=0
    while [ $elapsed -lt $max_wait ]; do
        local api_health
        api_health=$(curl -sf http://localhost:8000/health 2>/dev/null || echo "")
        if echo "$api_health" | grep -q "healthy"; then
            break
        fi
        sleep 5
        elapsed=$((elapsed + 5))
        echo -n "."
    done
    echo ""

    if [ $elapsed -ge $max_wait ]; then
        warn "Services may still be starting. Check with: docker compose ps"
    else
        log "All services healthy."
    fi
}

print_summary() {
    echo ""
    echo -e "${GREEN}${BOLD}============================================================${NC}"
    echo -e "${GREEN}${BOLD}  AEGIS Installation Complete${NC}"
    echo -e "${GREEN}${BOLD}============================================================${NC}"
    echo ""
    echo -e "  ${BOLD}Dashboard:${NC}  http://localhost:3000"
    echo -e "  ${BOLD}API:${NC}        http://localhost:8000"
    echo -e "  ${BOLD}API Docs:${NC}   http://localhost:8000/docs"
    echo -e "  ${BOLD}Health:${NC}     http://localhost:8000/health"
    echo ""
    echo -e "  ${BOLD}Manage:${NC}"
    echo "    docker compose ps          # Service status"
    echo "    docker compose logs -f     # Follow logs"
    echo "    docker compose down        # Stop all"
    echo "    docker compose up -d       # Start all"
    echo ""
    echo -e "  ${BOLD}Setup wizard (optional):${NC}"
    echo "    python3 scripts/setup-wizard.py"
    echo ""
    echo -e "  ${BOLD}Next steps:${NC}"
    echo "    1. Set your OPENROUTER_API_KEY in .env"
    echo "    2. Restart: docker compose restart aegis-api"
    echo "    3. Open http://localhost:3000"
    echo ""
}

# --- Main ---

main() {
    banner
    check_docker
    check_compose
    check_ports
    setup_directory
    clone_or_download
    create_env
    build_and_start
    print_summary
}

main "$@"
